version: '3'
services:
  backendapp:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: farmacopea/nodejs
    restart: always
    depends_on:
      - mysql
    networks:
      - backend
      - frontend
    expose:
      - 30001
    environment:
      VIRTUAL_HOST: localhost/services/m
      APP_PORT: 30001
      MYSQL_HOST: mysql-farmacopea
      MYSQL_USER: farmacopea
      MYSQL_PASS: 123
      MYSQL_DB: farmacopeadb
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER:
      SMTP_PASS:
      UPLOADS_FOLDER: /var/www/html
      SECRET_KEY: 4l9uN4114v3s3Er37A
    volumes:
      - ./uploads/:/var/www/html
    container_name: backend-farmacopea
  reactjs:
    build:
      context: .
      dockerfile: Dockerfile-frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    image: farmacopea/reactjs
    depends_on:
      - backendapp
    networks:
      - frontend
      - backend
    environment: 
      VIRTUAL_HOST: farmacopea.informatica.uv.cl
    expose:
      - 80
    volumes:
      - ./uploads/:/var/www/html
    container_name: frontend-farmacopea
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: farmacopea
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: farmacopeadb
    volumes:
      - ./database/:/var/lib/mysql
      - ./api-rest/database:/tmp/database
    container_name: mysql-farmacopea
networks:
  frontend:
    external:
      name: nginx-proxy
  backend:
