FROM node:latest as builder

ARG REACT_APP_SERVICES_HOST=/services/m

WORKDIR /app

COPY ./frontend/package*.json ./

RUN npm install --silent

COPY ./frontend ./

RUN npm run --silent build
# ------------------------------------------------------
# Production Build
# ------------------------------------------------------
FROM nginx:1.16.0-alpine

COPY --from=builder /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

